### ISSUE TITLE
Jet Set Radio graffiti control issues

### ISSUE THREAD

**Issue by Lakemu** [flyinghead/flycast#1017]
Platform: Windows 10
Github hash: 92a1c18
Hardware: Intel Core i5 8th Gen, Nvidia GeForce 930MX, 8gb RAM

**_Description of the Issue and Debugging Steps Tested_**

The graffiti making controls in Jet Set Radio are not functioning properly. Apparently this is a known issue in that joystick movement via keyboard is basically not registered other than 0% or 100%. But this being an emulator with the goal of playing the Dreamcast games on pc, it would be highly recommendable that this functionality becomes usable, because many people would prefer playing it this way too. Not to mention it's still not working properly with a gamepad either. It's also been seen to be possible in other emulators anyways. It does need to be eventually resolved.

The first graffiti movement encountered in the game is a simple "down" movement. Please keep that in mind in the following more detailed explanations.

Firstly, it's not working via keyboard. The singular "down" movement will not be registered at all no matter what. It's actually supposed to be literally just down. If I use a gamepad and get past the "down" movement, the next movements like "slide from up to down" and "slide from down to up" do actually register almost completely fine via keyboard. So it is practically possible for the keyboard to function well after all? Perhaps the movement detection needs to be extended for the single direction movement? Increased sensitivity or something? I don't know what's internally going on, but it is actually possible for the keyboard to register, as seen with the later more complex movements asked by the game to be performed.

Secondly, it's still not working via gamepad. Again the exact same situation. I have a classic third-party DInput gamepad, not an XInput gamepad. The singular "down" movement is still not being registered. If I force myself doing some crazy movements, like repeatedly going from up to down or something, it will eventually register after about five tries and get past the "down" movement. Then the following more complex movements like "slide from up to down" and "slide from down to up" do again register successfully.

So the issue with keyboard and gamepad is actually identical. And has to do with the less complex singularly directed movements. Seems to have to do with sensitivity somehow, that would be my guess, but it could be anything else too, as I don't really know.

I'm not sure what could be done about it but this is what is going on. The game is really impossible to be played like this, because the "down" movement comes up often. Hopefully this can be eventually fixed.

Cheers.

**_Screenshots_**

Here are some movement examples as I referred to above.

![1](https://user-images.githubusercontent.com/70599421/232868914-11c26a7f-2ecb-4fdf-8a1d-38a37d6bac87.png)
a singular "down" movement

![2](https://user-images.githubusercontent.com/70599421/232868928-443ae823-0752-4f2e-b8d9-2933a14cb912.png)
a "slide from down to up" movement

![3](https://user-images.githubusercontent.com/70599421/232868944-bcf4e540-a436-430d-88e1-43c4eb8b7555.png)
"slide from up to down" and "slide from down to up" movements

**Comment by flyinghead** [comment]
As explained on Discord, the keyboard issue is expected since it emulates analog axes with fixed values: -100%, 0% or +100%. So if the game is expected some intermediate values, it won't work.

However it should work fine with a regular gamepad if it has an analog stick. Does your gamepad have an analog left stick, and is it mapped as such with flycast?

**Comment by Leafdomain** [comment]
Yes it does. It looks exactly like a PS2 controller, if that gives an idea. And yes, it's mapped properly to the axes. Here's a picture.
![x](https://user-images.githubusercontent.com/70599421/232871803-b88fcf2f-1a2e-4302-a756-8be9cd54b107.png)

Also, the movement that doesn't work is actually the one that expects a fixed 100%. The "directly down" movement is the one that's not working. The sliding movements do actually work.

I mean, I'm assuming it's 100% down. Because it looks like this:
![1](https://user-images.githubusercontent.com/70599421/232872097-db67dc49-a1f0-4699-b0d6-ce1d5ff35c10.png)

Wouldn't you also assume so?

So what would you think could possibly causing the direct 100% one not to work?

**Comment by flyinghead** [comment]
What kind of gamepad do you have?

Flycast uses SDL to get inputs from gamepads, and it's supposed to normalize axes input from -32768 to +32767. A possible explanation would be that your gamepad axes report a smaller range, which JSR rejects for this graffiti movement.

Do you have any other gamepad model you could test with?

**Comment by Leafdomain** [comment]
Unfortunately no, I don't have any other gamepad as they're not affordable here.

My gamepad works completely fine in all other emulators and games, I never ran into any issue in anything else.

How can I check if my gamepad uses SDL?
As far as I'm aware, it's using DInput, if that's related.

**Comment by flyinghead** [comment]
SDL is just a library used by many games and emulators, including flycast and redream.

**Comment by Leafdomain** [comment]
Well then I guess it's compatible with my gamepad, because my gamepad does get detected and is usable in everything that allows DInput.

Well I'm not sure what else to say really but if you need any testing or any other info or anything else from me about this, I'm here...

**Comment by flyinghead** [comment]
You can try this test CDI: http://www.cosmicbreaks.com/arcade/downloads/ControllerTest-DJ.zip

It doesn't give precise information on the axes values but it's still a good utility.

**Comment by Leafdomain** [comment]
Tested the program. Everything seems to be working as intended. I'm getting different axes values according to how much in which direction I'm pressing. I'm correctly getting different sensitivity values for inbetween axes. For example, if I'm pressing diagonally, it will correctly show the involved axes as halved. So everything seems to be working properly.

But then again, the issue with JSR is with the "down" movement, which is just directly downwards, no inbetween axes involved. Why would just "down" not be recognized by the game, both on keyboard and gamepad?

**Comment by flyinghead** [comment]
You can now adjust dead zone and saturation for analog axes, which should help with this issue if still present.

**Comment by flyinghead** [comment]
Fixed in the latest `dev` build

**Comment by Lakemu** [comment]
Tested it. Finally works completely fine on keyboard and JSR is ultimately enjoyable. Thank you! :)

**Comment by Kingcangri** [comment]
> Tested it. Finally works completely fine on keyboard and JSR is ultimately enjoyable. Thank you! :)

How were you able to correct this issue? Im having the same issue on retroarch PSC with a PS4 controller

**Comment by Windsurf7** [comment]
The retroarch core might be an older version where this wasn't fixed. Try the standalone emulator.

**Comment by captainskoden** [comment]
I have the same problem and I'm playing it using a D-pad on the RG35XXSP anbernic w/ Flycast. I changed my controls to left analog and everything works fine except for the arrow graffiti, how do I fix it?
