### ISSUE TITLE
[Linux\openSUSE Leap 15.6\Vulkan] Flycast crashes and freezes when resizing its window

### ISSUE THREAD

**Issue by cinnamonmatexfce** [flyinghead/flycast#1620]
- *git describe --tags*
```
v2.3.2-181-g308d9fc1a
```

</br>

 - *flycast*
```
00:00:000 sdl/sdl.cpp:734 N[RENDERER]: Monitor refresh rate: 0 Hz (1920 x 1080)
00:00:019 ui/gui.cpp:330 N[RENDERER]: Screen DPI is 94, size 1846 x 1052. Scaling by 1.00
00:00:176 rend/gles/gles.cpp:637 N[RENDERER]: OpenGL version 4.3
00:00:176 rend/gles/gles.cpp:638 N[RENDERER]: Vendor 'NVIDIA Corporation' Renderer 'NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2' Version '4.3.0 NVIDIA 550.100'
00:00:180 sdl/sdl_gamepad.h:179 N[INPUT]: SDL: Opened joystick 0 on port 0: 'DualSense Wireless Controller' unique_id=sdl_joystick_0
00:06:164 sdl/sdl.cpp:734 N[RENDERER]: Monitor refresh rate: 0 Hz (1920 x 1080)
00:06:174 rend/vulkan/vulkan_context.cpp:245 N[RENDERER]: Vulkan API 1.1. Device NVIDIA GeForce GTX 1660 SUPER
00:06:174 rend/vulkan/vulkan_context.cpp:253 N[RENDERER]: eR5G5B5A1UnormPack16 not supported for optimal tiling
00:06:174 rend/vulkan/vulkan_context.cpp:267 N[RENDERER]: eR4G4B4A4UnormPack16 not supported for optimal tiling
00:06:223 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:06:233 rend/vulkan/oit/oit_renderer.cpp:32 N[RENDERER]: OITVulkanRenderer::Init
00:06:267 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:10:293 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:10:304 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:19:762 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:19:787 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:19:812 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:19:834 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:19:869 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
```

</br>

- *LC_ALL=C sudo zypper -s11 se -ids /^nvidia/*
```
Loading repository data...
Reading installed packages...

S   Name                           Type     Version                              Arch    Repository

i   nvidia-compute-G06             package  550.100-lp156.25.1                   x86_64  repo-non-free (15.6)
i   nvidia-compute-G06-32bit       package  550.100-lp156.25.1                   x86_64  repo-non-free (15.6)
i   nvidia-compute-utils-G06       package  550.100-lp156.25.1                   x86_64  repo-non-free (15.6)
i   nvidia-driver-G06-kmp-default  package  550.100_k6.4.0_150600.21-lp156.25.1  x86_64  repo-non-free (15.6)
i+  nvidia-drivers-G06             package  550.100-lp156.25.1                   x86_64  repo-non-free (15.6)
i   nvidia-gl-G06                  package  550.100-lp156.25.1                   x86_64  repo-non-free (15.6)
i   nvidia-gl-G06-32bit            package  550.100-lp156.25.1                   x86_64  repo-non-free (15.6)
i   nvidia-utils-G06               package  550.100-lp156.25.1                   x86_64  repo-non-free (15.6)
i   nvidia-video-G06               package  550.100-lp156.25.1                   x86_64  repo-non-free (15.6)
i   nvidia-video-G06-32bit         package  550.100-lp156.25.1                   x86_64  repo-non-free (15.6)
```

</br>

- *LC_ALL=C sudo zypper -s11 se -ids gcc*
```
Loading repository data...
Reading installed packages...

S   Name                         Type     Version                       Arch    Repository

i   cpp7                         package  7.5.0+r278197-150000.4.41.1   x86_64  repo-oss (15.6)
i   cpp13                        package  13.3.0+git8781-150000.1.12.1  x86_64  update-sle (15.6)
i   dwarves                      package  1.25-150600.1.4               x86_64  repo-oss (15.6)
i   gcc                          package  7-3.9.1                       x86_64  repo-oss (15.6)
i+  gcc-c++                      package  7-3.9.1                       x86_64  repo-oss (15.6)
i   gcc7                         package  7.5.0+r278197-150000.4.41.1   x86_64  repo-oss (15.6)
i   gcc7-c++                     package  7.5.0+r278197-150000.4.41.1   x86_64  repo-oss (15.6)
i   gcc13                        package  13.3.0+git8781-150000.1.12.1  x86_64  update-sle (15.6)
i+  gcc13-c++                    package  13.3.0+git8781-150000.1.12.1  x86_64  update-sle (15.6)
i   libasan4                     package  7.5.0+r278197-150000.4.41.1   x86_64  repo-oss (15.6)
i   libasan8                     package  13.3.0+git8781-150000.1.12.1  x86_64  update-sle (15.6)
i   libatomic1                   package  13.3.0+git8781-150000.1.12.1  x86_64  update-sle (15.6)
i   libcilkrts5                  package  7.5.0+r278197-150000.4.41.1   x86_64  repo-oss (15.6)
i   libdwarves1                  package  1.25-150600.1.4               x86_64  repo-oss (15.6)
i   libgcc_s1                    package  13.3.0+git8781-150000.1.12.1  x86_64  update-sle (15.6)
i   libgcc_s1-32bit              package  13.3.0+git8781-150000.1.12.1  x86_64  update-sle (15.6)
i   libhwasan0                   package  13.3.0+git8781-150000.1.12.1  x86_64  update-sle (15.6)
i   libitm1                      package  13.3.0+git8781-150000.1.12.1  x86_64  update-sle (15.6)
i   liblsan0                     package  13.3.0+git8781-150000.1.12.1  x86_64  update-sle (15.6)
i   libmpx2                      package  8.2.1+r264010-150000.1.6.4    x86_64  repo-oss (15.6)
i   libmpxwrappers2              package  8.2.1+r264010-150000.1.6.4    x86_64  repo-oss (15.6)
i   libstdc++6-devel-gcc7        package  7.5.0+r278197-150000.4.41.1   x86_64  repo-oss (15.6)
i   libstdc++6-devel-gcc13       package  13.3.0+git8781-150000.1.12.1  x86_64  update-sle (15.6)
i   libtsan0                     package  11.3.0+git1637-150000.1.11.2  x86_64  repo-oss (15.6)
i   libtsan2                     package  13.3.0+git8781-150000.1.12.1  x86_64  update-sle (15.6)
i   libubsan0                    package  7.5.0+r278197-150000.4.41.1   x86_64  repo-oss (15.6)
i   libubsan1                    package  13.3.0+git8781-150000.1.12.1  x86_64  update-sle (15.6)
i   openSUSE-SLE-15.6-2024-1498  patch    1                             noarch  update-sle (15.6)
i   openSUSE-SLE-15.6-2024-2086  patch    1                             noarch  update-sle (15.6)
i   openSUSE-SLE-15.6-2024-2172  patch    1                             noarch  update-sle (15.6)
i   openSUSE-SLE-15.6-2024-2203  patch    1                             noarch  update-sle (15.6)
i   openSUSE-SLE-15.6-2024-2393  patch    1                             noarch  update-sle (15.6)
i   openSUSE-SLE-15.6-2024-2586  patch    1                             noarch  update-sle (15.6)
i   openSUSE-SLE-15.6-2024-2802  patch    1                             noarch  update-sle (15.6)
i   openSUSE-SLE-15.6-2024-2933  patch    1                             noarch  update-sle (15.6)
```

</br>

- *uname -sro && nvidia-smi -L && cat /etc/os-release*
```
Linux 6.4.0-150600.23.17-default GNU/Linux
GPU 0: NVIDIA GeForce GTX 1660 SUPER (UUID: GPU-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
NAME="openSUSE Leap"
VERSION="15.6"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.6"
PRETTY_NAME="openSUSE Leap 15.6"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.6"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
```

</br>

- *screenshot*
![flycast_crash](https://github.com/user-attachments/assets/69ced4f6-802e-460a-bc75-d43f94b0bbee)

</br>

- *attachments*
  - [emu.cfg](https://github.com/user-attachments/files/16782786/emu.cfg.txt)
  - [vulkaninfo](https://github.com/user-attachments/files/16782788/vulkaninfo.txt)

**Comment by flyinghead** [comment]
Can you install the Vulkan SDK and run the app with validation layers enabled?

I run ubuntu with proprietary nvidia drivers 535 and no crash while resizing and no validation error.

**Comment by cinnamonmatexfce** [comment]
> EDIT: Also crashing and freezing aren't the same thing. If crashing, running under a debugger might help.

Mmm... I *think* it's only freezing, yes, but there's no way for me to quit unless I `pkill flycast`...

</br>

> Can you install the Vulkan SDK and run the app with validation layers enabled?
```
export VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation
export VK_LOADER_LAYERS_ENABLE=*validation
flycast
```
Here's an extract of Konsole's output flooded with:
```
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0x1a000000001a0, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0x1a000000001a0, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0x1a400000001a4, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0x1a400000001a4, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0x19c000000019c, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0x19c000000019c, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0x1a000000001a0, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0x1a000000001a0, type: 5, name: NULL
00:11:862 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:11:881 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:11:920 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:11:938 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:11:977 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:11:996 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:003 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:055 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:094 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:113 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:122 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:163 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:181 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:219 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:237 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:288 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:332 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:349 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:398 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:429 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:450 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:484 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:502 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:551 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:590 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:610 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:619 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:662 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:692 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:710 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:742 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:758 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:766 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:808 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:838 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:854 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:886 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:902 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:12:947 rend/vulkan/vulkan_context.h:271 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0b0000000b0b, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0b0000000b0b, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0f0000000b0f, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0f0000000b0f, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb070000000b07, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb070000000b07, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0b0000000b0b, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0b0000000b0b, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0f0000000b0f, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0f0000000b0f, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb070000000b07, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb070000000b07, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0b0000000b0b, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0b0000000b0b, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0f0000000b0f, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0f0000000b0f, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb070000000b07, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb070000000b07, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0b0000000b0b, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0b0000000b0b, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0f0000000b0f, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0f0000000b0f, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb070000000b07, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb070000000b07, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0b0000000b0b, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0b0000000b0b, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0f0000000b0f, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0f0000000b0f, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb070000000b07, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb070000000b07, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0b0000000b0b, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0b0000000b0b, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0f0000000b0f, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0f0000000b0f, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb070000000b07, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb070000000b07, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0b0000000b0b, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0b0000000b0b, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0f0000000b0f, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0f0000000b0f, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb070000000b07, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb070000000b07, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0b0000000b0b, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0b0000000b0b, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0f0000000b0f, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0f0000000b0f, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb070000000b07, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb070000000b07, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0b0000000b0b, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0b0000000b0b, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0f0000000b0f, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0f0000000b0f, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb070000000b07, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb070000000b07, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0b0000000b0b, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0b0000000b0b, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0f0000000b0f, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0f0000000b0f, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb070000000b07, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb070000000b07, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0b0000000b0b, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0b0000000b0b, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0f0000000b0f, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0f0000000b0f, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb070000000b07, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb070000000b07, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0b0000000b0b, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0b0000000b0b, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb0f0000000b0f, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb0f0000000b0f, type: 5, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01779(ERROR / SPEC): msgNum: 1461184347 - Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xb070000000b07, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
    Objects: 1
        [0] 0xb070000000b07, type: 5, name: NULL
```

NOTE: when exporting `VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation` and `VK_LOADER_LAYERS_ENABLE=*validation`, Flycast no longer freezes while resizing its windows

**Comment by flyinghead** [comment]
This is a new validation error check introduced in Vulkan SDK 1.3.275 (I was running 1.3.239). For this reason I doubt this is the cause of the freeze. I have a fix for it though.

I suppose validation layers have some side effect that avoids the issue, but having them enabled all the time isn't really a solution. Also there's no error when actually resizing the window so I still don't have any clue.

**Comment by cinnamonmatexfce** [comment]
> I suppose validation layers have some side effect that avoids the issue, but having them enabled all the time isn't really a solution

Nope, sorry, Flycast freezes also with *validations* enabled anyways (I edited my previous comment)

**Comment by cinnamonmatexfce** [comment]
I was also able to test Flycast on ArchLinux.
Upon further investigation here are the updates to the problem:
 - Flycast also freezes on ArchLinux
 - the freezing (in both openSUSE and ArchLinux) occurs only when resizing the window if inside the **SETTINGS** section

**Comment by flyinghead** [comment]
I have pushed a fix for the repeating vulkan validation error.
Unfortunately I still can't reproduce the freeze even when in the Settings.
'll have a look at this last validation error (VUID-VkPresentInfoKHR-pImageIndices-01430) since it might be a good clue.

**Comment by flyinghead** [comment]
I pushed a fix on master and dev where I was having similar freeze and errors when resizing.
Can you give it a try?

**Comment by cinnamonmatexfce** [comment]
> I pushed a fix on master and dev where I was having similar freeze and errors when resizing. Can you give it a try?

It works like a charm!! 💪🏼

Thank you, dear @flyinghead !! 🧡

**Comment by flyinghead** [comment]
Great news! thank you for your quick feedback

**Comment by Vamp898** [comment]
Not sure if i am really hitting the same bug.

Resizing works for me, but when going fullscreen, the freeze still happens for me.

Only happens when using Vulkan. Not using nVidia but Radeon though.

**Comment by cinnamonmatexfce** [comment]
> 
> Resizing works for me, but when going fullscreen, the freeze still happens for me.
> 


  
  
@Vamp898 Mmm... I've just done some tests on *openSUSE* also (built from [latest](https://github.com/flyinghead/flycast/commit/4320685ff8d5f6e55ad154dca7bdf83d2b38555d) `dev`, this time): I can confirm everything's still working properly with Vulkan and nVIDIA (maximize, minimize, resize, fullscreen).

```
git branch --show-current && git submodule status && git status && git show --oneline -s
dev
 3a68b89c7a5f3597b1ffa40d10eaf93c1521262c core/deps/DreamPicoPort-API (v1.0.1)
 00d4f1c2c4ad2dc95d26b18743541f57b1dca56d core/deps/SDL (release-2.32.0-122-g00d4f1c2c)
 2110a918e720688f3cb2118302fd153db8745ace core/deps/Spout (remotes/origin/fix-shlwapi)
 486dd8e4ef3bead482ea26de99770f4389e24e37 core/deps/Syphon (heads/main)
 85c2334e92e215cce34e8e0ed8b2dce4700f4a50 core/deps/Vulkan-Headers (v1.3.261-2-g85c2334)
 6eb62e1515072827db992c2befd80b71b2d04329 core/deps/VulkanMemoryAllocator (v2.1.0-810-g6eb62e1)
 d3402006e84efb6114ff93e4f2b8508412ed80d5 core/deps/asio (asio-1-32-0-1-gd3402006)
 1ab24bcc817ebe629bf77daa53529d02361cb1e9 core/deps/breakpad (heads/main)
 c62c34d37cd90b75187a1212e13ce4145bafbdd7 core/deps/discord-rpc (v3.1.0-70-gc62c34d)
 fc9889c889561c5882e83819dcaffef5ed45529b core/deps/glslang (11.1.0-1230-gfc9889c8)
 e39786088138f2749d64e9e90e0f9902daa77c40 core/deps/googletest (release-1.8.0-3482-ge3978608)
 8fae8ce254dfc1344527e05301e43f37dea2df80 core/deps/libadrenotools (v1.0-18-g8fae8ce)
 5f82799f2c8cad1e9cd26d39a0f8d36369a5534b core/deps/libchdr (heads/master)
 77daa8befd828046169adbb012d8de928bfdcdd4 core/deps/libjuice (v1.6.0)
 000e06eb241927db0f34e6867637d39b849ab989 core/deps/libusb-cmake (v1.0.29-0-2-g000e06e)
 5d21e35633a1f87ed08af115b07d3386096f792b core/deps/luabridge (0.2.2b-344-g5d21e35)
 a81bb9f87d4105b84b682685d3bfbb5beca371d1 core/deps/oboe (1.5.1-669-ga81bb9f8)
 3106e6d3d274b63c59976cb07dda94a292ab45ca core/deps/rcheevos (v11.6.0)
 1b11fd301531e6df35a6107c1e8665b1e77a2d8e core/deps/websocketpp (0.8.2-1-g1b11fd3)
 0d67fd1530016b7c56f3cd74b3fca920f4c3e2b4 core/deps/xbyak (v3.71-1460-g0d67fd1)
On branch dev
Your branch is up to date with 'origin/dev'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        _building_flycast/

nothing added to commit but untracked files present (use "git add" to track)
4320685ff (HEAD -> dev, origin/dev) uwp: simplify activation and exit URIs handling
```

**Comment by Vamp898** [comment]
@cinnamonmatexfce It is fixed by this https://github.com/flyinghead/flycast/issues/2082#issuecomment-3527215004
