### ISSUE TITLE
Problems with MSVC build

### ISSUE THREAD

**Issue by mfigueirido** [flyinghead/flycast#1911]
Platform / OS / Hardware: 
Windows 11 x64

Flycast version: 
2ca596ae204cdeb9eef77e040db9bf5935a37b71 (latest)

Hardware: 
x64 based

**_Description of the Issue_**

First I would like to mention that it's my first time trying to build Flycast or a C++ application whatsoever, so apologies in advance if these issues are due to my lack of knowledge. I'm having a series of problems building/debugging Flycast in Visual Studio.

**_Debugging Steps Tested_**

1. After updating to latest master and updating submodules as well, I open Flycast source in Visual Studio 2022 and it attempts to generate CMake, process that fails with these errors:
![Image](https://github.com/user-attachments/assets/42dcb04c-72c1-4a06-b971-6e6a47de59ea)

This is the generated log:
[Generate CMake.log](https://github.com/user-attachments/files/19825924/Generate.CMake.log)

2. This leads me to try with a different commit. I switch back to 0f18e2e1674ffa4dc0232ea37128ca3047925640, which is the commit just before some changes were introduced for CMake. This time CMake generation is successful.

3. Now I try to build Flycast and a compile time error shows up in dcnet.cpp:
![Image](https://github.com/user-attachments/assets/6950dc5a-b56c-4ca8-9365-925d5994ab2d)

I look up in the internet and it turns out MSVC does not recognise ```ssize_t``` but it does if it's written all in caps: ```SSIZE_T```. After changing this Flycast.exe is built correctly.

4. I launch the app, select a game folder and all seems fine:
![Image](https://github.com/user-attachments/assets/98c32e89-b32a-40d4-b651-0a0e258dcf80)

But after selecting a game to load (Crazy Taxi for example) there's a crash in blockmanager.cpp:
![Image](https://github.com/user-attachments/assets/8e2d550e-06c1-4d84-9b10-f9ba4e3fb144)
![Image](https://github.com/user-attachments/assets/f407a5df-fd6b-4f53-827d-eeb10f92e54d)

I tried looking for causes of the crash but found nothing obvious to me.

5. After this I try building Flycast with MinGW so I execute:
```cmake -S .../flycast -B .../flycast/build -G "MinGW Makefiles"```
```cmake --build .../flycast/build```

Flycast.exe is built and it works perfectly in-game:
![Image](https://github.com/user-attachments/assets/99a27bc7-fe83-43ee-85fa-e74f1939d5e7)

I would like to debug Flycast from Visual Studio though, not only build the exe. Any ideas of why the MSVC build crashes but the MinGW one does not?

Thanks for your time.

**Comment by flyinghead** [comment]
You might have to upgrade cmake to version 4.0 since it's the version used for building flycast.

The `ssize_t` issue in dcnet is fixed by 3193d2cf5d1b02e103c1a01b24adc3999c5f3a58.

Debugging flycast while running a game is difficult and I don't think it's possible with MSVC. The reason is flycast makes a lot of memory protection faults, which are normally programming errors but are not in this case.
Unfortunately MSVC (and other IDEs) is stubborn and persists in treating these exceptions as programming errors.

**Comment by mfigueirido** [comment]
Actually, debugging with VS works! I feel so dumb... Loading a game with the MinGW build is almost instant, the MSVC build is just super slow loading a game leaving the impression of being freezed but after that I can debug the application.

Thanks for everything, I'll close this.

**Comment by flyinghead** [comment]
Using `Debug` builds isn't recommended because they are very slow, and generate lots of logging by default. Use the `RelWithDebInfo` build configuration instead, which has all the debugging symbols but runs as fast as the release build.

**Comment by mfigueirido** [comment]
Thanks for the tip! By the way updated CMake to 4.0 and the generation still fails with the same errors, but if it's working for you that means it's something I'm not doing correctly on my end.
