### ISSUE TITLE
[Vulkan] Graphic Bugs on MVC2 and SNKvsCapcom 1 and 2

### ISSUE THREAD

**Issue by MagnusPrime12** [flyinghead/flycast#197]
**Platform / OS / Hardware: **
Windows 10, RX 480, Latest Radeon Drivers, Ryzen 2600

**_Description of the Issue_**

Hard to describe, but per screenshot, you can see small faint vertical lines coming down, picture reference the hand on Guile and the Ryu Super Hadoken. This happens only to the human character, not the CPU character. Almost like a "tile" effect. Faint, but annoying. 

**_Debugging Steps Tested_**

-Only happens when Vulkan is on and I tweaked with the various other settings
-Does not happen with OGL

**_Screenshots_**

![62546656-2cd66800-b864-11e9-8d95-9095b20dde20](https://user-images.githubusercontent.com/79935256/109821136-af233b80-7c03-11eb-9c7e-1a16341b34b0.png)
![Screenshot_1](https://user-images.githubusercontent.com/79935256/109821138-af233b80-7c03-11eb-9b8d-ddb1187ce3bb.jpg)

**Comment by flyinghead** [comment]
These are upscaling artifacts. If you set the window resolution to 640x480, they will disappear. Also, using a multiple of the native 640x480 resolution does help.

**Comment by MagnusPrime12** [comment]
@flyinghead , Does the emulator has a setting for windows resolution? I didn't see it in the setting. Are you asking me to set the my desktop resolution to 640x480 and then run the emulator? My windows screen is set to 1920x1080 right now. It's a 47inch, I will go blind lol.

**Comment by MagnusPrime12** [comment]
@flyinghead, here is another picture I took with the latest 3/3 build. The strange thing is it's only happening with the human player, the cpu as you can see has no artifacts. So very strange.

<img width="479" alt="Capture" src="https://user-images.githubusercontent.com/79935256/109839784-768c5d80-7c15-11eb-98f5-3512ebe34aa7.PNG">

**Comment by flyinghead** [comment]
Right now you can only change the screen resolution/window size, or change the `Scaling` option in Video. Setting it to 0.5 will halve the vertical and horizontal resolution. So 1920x1080 will become 960x540.

I'm working on simplifying this.

**Comment by MagnusPrime12** [comment]
Thanks for helping on this one. That would be an awesome addition if you can select it. Right now that ratio won't exactly hit a 640x480.

**Comment by Gamemulatorer** [comment]
I have a graphics issue on MVC2 on my Redmi Note 9 :(
![Screenshot_2021-05-03-23-24-43-712_com flycast emulator](https://user-images.githubusercontent.com/37603562/116896624-05921200-ac67-11eb-9247-d6a31867242d.jpg)
![Screenshot_2021-05-03-23-24-17-544_com flycast emulator](https://user-images.githubusercontent.com/37603562/116896629-075bd580-ac67-11eb-9b42-56c67c480259.jpg)
![Screenshot_2021-05-03-23-23-43-062_com flycast emulator](https://user-images.githubusercontent.com/37603562/116896639-09259900-ac67-11eb-904e-dec0aea068d9.jpg)
I tried both OGL and VK still the same

**Comment by flyinghead** [comment]
I assume this is a regression. Any idea at which build it started?

**Comment by Gamemulatorer** [comment]
> I assume this is a regression. Any idea at which build it started?

It's ok now I just deleted the emu.cfg file and use your latest git build apk.

**Comment by Gamemulatorer** [comment]
But I still have some display issue like this
![Screenshot_2021-05-03-23-37-22-375_com flycast emulator](https://user-images.githubusercontent.com/37603562/116898657-3a9f6400-ac69-11eb-92a3-65aab79c41ff.jpg)
Does flycast doesn't support fullscreen on a phone with noth or punch hole?

**Comment by flyinghead** [comment]
This is precisely due to Flycast now supporting Android notch: the game renders on the entire screen but the UI is shifted to not cover the notch. So the background isn't completely covered.

**Comment by flyinghead** [comment]
Fixed

**Comment by Gamemulatorer** [comment]
> Fixed

which commit fix this issue?

**Comment by flyinghead** [comment]
This one in particular: https://github.com/flyinghead/flycast/commit/1abfa19636252e71200684747cd1df38d55a97fa#diff-393895d5f043a03a524a3cab752fa4ca4e2a27a80cbf62df6997b3e6cdef20b5
Using multiples to native resolution greatly helps.

**Comment by Gamemulatorer** [comment]
There's still glitch using the commit you mention.
![Screenshot_2021-11-29-11-02-41-364_com flycast emulator](https://user-images.githubusercontent.com/37603562/143802246-b31b9ccf-5088-4930-8d95-c79b4e2b15ad.jpg)

**Comment by DJRM2021** [comment]
This issue still happens on the latest build.

![image](https://user-images.githubusercontent.com/77593544/224606505-b2583811-7ce9-48fb-b184-8ab4e69dddd7.png)
Settings:
![image](https://user-images.githubusercontent.com/77593544/224606021-c0076484-2cae-4d53-b33f-3a50af9bfd77.png)
![image](https://user-images.githubusercontent.com/77593544/224606060-fe14b116-a532-4644-b3f9-afd898148ea5.png)


Samples:
![image](https://user-images.githubusercontent.com/77593544/224606441-17d0adc3-98b0-495c-8cc0-735869b91ddf.png)
![image](https://user-images.githubusercontent.com/77593544/224606455-c4423f25-b5e6-4eac-b3f7-3a380f96a6fe.png)
