### ISSUE TITLE
Flyscast x64 closing on game launch since releaser7-rc1-3231-g0c881554

### ISSUE THREAD

**Issue by fpushin** [flyinghead/flycast#198]
Platform / OS / Hardware: 

OS : Windows 10 pro  x64
CPU : Celeron J4125 
RAM :  6 GB
Graphic card : Intel UHD 600

All drivers up to date.

Github hash: 0c881554

 

**_Description of the Issue_**

The emulator is closing when I try to launch a game since the release 0c881554 from 2021-03-02T18:47:02 (it hangs when logs are enabled). Older versions work well with the same CFG and I also tried with a clean folder from scratch.
I tried both OpenGL and Vulkan (Vulkan never worked on this PC with older version btw). The newer releases work fine on my other PCs with a NVidia or AMD card.

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```
00:00:000 hw/mem/_vmem.cpp:496 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:00:038 hw/mem/_vmem.cpp:496 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:00:071 ./nullDC.cpp:96 N[BOOT]: Game ID is [MK-5100250]
00:01:203 windows/winmain.cpp:204 E[COMMON]: [GPF] PC 00007ffee767ccf5 unhandled access to 0000000000000000
00:01:203 windows/winmain.cpp:204 E[COMMON]: [GPF] PC 00007ffee767ccf5 unhandled access to 0000000000000000
00:01:203 windows/winmain.cpp:204 E[COMMON]: [GPF] PC 00007ffee767ccf5 unhandled access to 0000000000000000

(the last line repeats until I kill the process)


```

Thank you for your great work :-)

**Comment by flyinghead** [comment]
Does using the interpreter make any difference?

I don't think this is a graphics issue since this commit didn't change anything in this area. It might be a CPU instruction not supported by your CPU model.

What CPU model does your other PC(s) have?

**Comment by fpushin** [comment]
I just tried the interpreter, it does the same thing.
i tried on AMD 5800x and a Intel I7 2600K without issues.

**Comment by jvhellraiser** [comment]
I get the same issue i just try the latest build and every single game a try to open closes automatically
so weird i am not able to open any chd,gdi at all

**Comment by flyinghead** [comment]
@jvhellraiser what CPU do you have?

Make sure it's the same issue: try vulkan vs. Open GL, per-triangle vs. per-pixel, etc. to rule out another problem.

Also, please post your log file.

**Comment by PhantomX** [comment]
Same here, started with [0c88155](https://github.com/flyinghead/flycast/commit/0c8815549c3ad0eccc619dd73aebbe973ac111a6).
[flycast.log](https://github.com/flyinghead/flycast/files/6108055/flycast.log)

OS : Fedora 33
CPU : AMD Phenom(tm) 9950 Quad-Core Processor (old, but flycast runs very well on it)
RAM : 8 GB
Graphic card : AMD Radeon RX 570

I tried with Vulkan, OpenGL, per-triangle, per-pixel, dynarec and interpreter.

SO log:
[ 5070.742380] traps: flycast[10825] trap invalid opcode ip:545da8 sp:7f3c8513bb90 error:0 in flycast[542000+400000]
[ 5096.770812] traps: flycast[10897] trap invalid opcode ip:545da8 sp:7fe2570a3b90 error:0 in flycast[542000+400000]
[ 5137.581565] traps: flycast[10962] trap invalid opcode ip:545da8 sp:7f9b4091eb90 error:0 in flycast[542000+400000]
[ 5173.684294] traps: flycast[11027] trap invalid opcode ip:545da8 sp:7f462d1f9bf0 error:0 in flycast[542000+400000]

**Comment by flyinghead** [comment]
I think I found the problem. One x86 instruction being used isn't available on ~~prehistoric~~ old CPU models. Thanks to @PhantomX for confirming it was due to an unsupported opcode.

Should be fixed in build https://github.com/flyinghead/flycast/commit/cb52d0b6ec0c49de4e546bb76c26a3683878191f.

**Comment by PhantomX** [comment]
Works for me now. Thanks!

**Comment by fpushin** [comment]
Last release working on my **venerable** older CPU ! ;-)

Thanks a lot for the fix, I can go back to my lightgun issue!

**Comment by jvhellraiser** [comment]
> 
> 
> @jvhellraiser what CPU do you have?
> 
> Make sure it's the same issue: try vulkan vs. Open GL, per-triangle vs. per-pixel, etc. to rule out another problem.
> 
> Also, please post your log file.
> 
> Do you know which build started to crash?

I am using Intel core i5 3470 CPU at 3.20ghz
8 gb ram , windows 10 between per- triangle or per-pixel 
the problem wont change it still crashes while trying to load GDI/CDI or CHD
about the log file i haven't post any cause Flycast wont write anything to the log is empty..Zero/Nada!
it was  Yesterdays build and it does it on today's build too.. Version:r7-rc1-3248-g99e37500

**Comment by flyinghead** [comment]
It's a different issue then. The only significant change in yesterday's build (99e37500) was related to Vulkan so it shouldn't make any difference with Open GL.

Can you confirm that the previous build (https://github.com/flyinghead/flycast/commit/478b9a9f6897d7e9a641dfb01c0d6f4537b2bb0e) is working fine?

**Comment by jvhellraiser** [comment]
It's a different issue then. The only significant change in yesterday's build (99e3750) was related to Vulkan so it shouldn't make any difference with Open GL.

Can you confirm that the previous build (478b9a9) is working fine?

I believe there is no need to test that build this build cb52d0b fixes the issue on loading CDI/GDI/CHD
