### ISSUE TITLE
DualShock 4 does not work correctly via Bluetooth in the latest emulator builds

### ISSUE THREAD

**Issue by OsbornX98** [flyinghead/flycast#2109]
Platform / OS / Hardware: 
Poco F5/ Android 13

Flycast version: 
v2.5-161-g922ca3e54

Description of the Issue:
I’ve been experiencing an issue with the newer versions of the emulator. When I connect my DualShock 4 to my phone via Bluetooth, I simply can’t use the emulator properly because the cursor keeps being pulled downward, as if the left analog stick were being pushed down on its own. I’ve tried using other DualShock 4 controllers — I have three — and all of them have the same problem. It becomes impossible to play this way. 

I tested the version from the Play Store and it works normally; this issue only happens in the latest master build versions.

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

/

![Image](https://github.com/user-attachments/assets/9b40971c-d114-49e2-b806-23b7e96d008c)

https://github.com/user-attachments/assets/e46bd6ac-1f81-4f2e-ba79-755b876935e5

**Comment by flyinghead** [comment]
Have you tried to remap the thumbstick axes? or to reset the mapping to default?

I see that the right thumbstick doesn't seem to be affected by the problem. Is it true or does it have the same issue?

There has been some changes in the way analog axes are handled in Flycast and it looks like this is an unfortunate consequence of these changes. So I'm trying to understand what's going on.

**Comment by OsbornX98** [comment]
I have reset the settings multiple times and have also uninstalled and reinstalled several recent versions, all of which exhibit the same issue. Regarding the right thumbstick, I have not experienced any problems; as mentioned previously, the issue lies with the down thumbstick

**Comment by OsbornX98** [comment]
I am able to play the Play Store version without any issues; the problem occurs only in the latest versions of the master build.

**Comment by flyinghead** [comment]
I meant the right-side thumbstick:

<img width="486" height="357" alt="Image" src="https://github.com/user-attachments/assets/6f5ce0bb-1e0d-41ae-80d6-cb3bce961753" />

Do you have the same issue with it?

Do the left and right analog triggers work fine?

**Comment by OsbornX98** [comment]
I have not encountered any issues with the right-side  thumbstick; as previously stated, the problem is limited to the left-side thumbstick.

**Comment by flyinghead** [comment]
Could you install this app? https://gamepad-tester.en.softonic.com/android
I would like you to move the left and right thumbsticks full left and right, and full up and down. And also the left and right triggers from 0% to 100%.
Please record a video or screenshots. And let me know if you see anything strange. Thank you.

**Comment by flyinghead** [comment]
Here is an example with an Xbox Series gamepad:

<img width="1080" height="2246" alt="Image" src="https://github.com/user-attachments/assets/e16c101c-7ea1-49b4-b229-d452c4ee3504" />

**Comment by OsbornX98** [comment]
![Image](https://github.com/user-attachments/assets/bdb3d05c-8591-472e-8c67-6fa2a15da456)
![Image](https://github.com/user-attachments/assets/1f951292-bb49-4c18-bd09-a6d3e1d81c6b)
![Image](https://github.com/user-attachments/assets/c9e4d947-6bf6-4e55-baa8-d4d896fd4e23)
![Image](https://github.com/user-attachments/assets/5f17c63f-221d-4976-ac39-58e09817ce0d)

**Comment by OsbornX98** [comment]
https://github.com/user-attachments/assets/b625276e-05c4-43b3-bcba-cba20ea78bed

**Comment by flyinghead** [comment]
Thanks a lot for this. This is very helpful.

One last question: do you see other devices listed in `Controls > Physical Devices` when you connect your DualShock 4?
such as `Sony Wireless Controller Motion Sensors` or `Sony Wireless Controller`.
I guess a screenshot of this page would help.

In the mean time I pushed some changes to the `master` branch. I'm not sure this will help but please install the latest build and let me know.

**Comment by OsbornX98** [comment]
Hi! I checked in the Gamepad Tester app, and only a single device shows up when I connect my DualShock 4:

Name: Wireless Controller Touchpad
Product: Vendor_054c_Product_09cc

No additional devices appear, such as “Sony Wireless Controller” or “Sony Wireless Controller Motion Sensors.”

![Image](https://github.com/user-attachments/assets/96a9b7fa-55d4-4879-9dfa-5dd7865d1789)

**Comment by OsbornX98** [comment]
Even after updating to the latest version of the master branch, the problem still persists.

**Comment by flyinghead** [comment]
Should be fixed on the master branch.

I actually had to buy a DualShock 4 controller to understand and fix the issue. And I don't think I would have been able to fix it without one.

**Comment by OsbornX98** [comment]
It’s back to normal. Thank you, and apologies for the inconvenience.
