### ISSUE TITLE
Small sprite glitch in Marvel vs. Capcom 2

### ISSUE THREAD

**Issue by HebuSan** [flyinghead/flycast#466]
Platform / OS / Hardware: 
Window 10 / libretro core, since more than 3 years (on any different retroarch / core versions released for three years)

Hardware: 
Intel Core i7 CPu and GTX 970M or AMD Ryzen 7 5800 and RTW3060  - Happens on both.

**_Description of the Issue_**
As soon as internal resolution is greater than 640 * 480, the are some sprites gltiches.
Mostly on Ryu's "Shinku Hadoken", but if you pay attention, also on Ryu's own sprite, and some fonts in the character selection screen.

More details here, as the bug was already reported here:
https://github.com/libretro/flycast/issues/596

It seems the issue has been acknowledged and fixed some time ago on reicast side (issue showned and listed as fixed with reicast 1.3):
https://twitter.com/inolen/status/1039226899250262017

I don't have the skills to fix the issue, but I am ready to help testing any patch if it can help.

**Comment by Immersion95** [comment]
This is the other issue you're talking about as the glitch was fixed in native : 
https://github.com/libretro/flycast/issues/818

CVS1 & MVC2 suffer from this at higher resolution and it's a shame :p

**Comment by HebuSan** [comment]
> This is the other issue you're talking about as the glitch was fixed in native : [libretro#818](https://github.com/libretro/flycast/issues/818)
> 
> CVS1 & MVC2 suffer from this at higher resolution and it's a shame :p
> 
> Please note that you are talking about redream and not reicast. I don't think @inolen would help :(

1. Sorry, you are right, redream fixed the issue, not reicast. updated.
2. I confirm there is no issue at native resolution, but for any higher resolution, the glitches are still there. 
-> Is it something known / that cannot / won't be fixed ?

Thanks for taking time to answer.

**Comment by Gamemulatorer** [comment]
https://github.com/flyinghead/flycast/issues/197#issuecomment-981247405

**Comment by Immersion95** [comment]
It would be so great if a fix can be found as there's problem with native res.

Those games have sprites that were drawn on CPS2 with different resolution so the pixels are not great with the ratio change. Only solution is to upscale so we can have pixel perfect sprites.

**Comment by Epyc7** [comment]
This is still happening, any fixes in sight?  This glitch has been around for years.

**Comment by yudhiyou** [comment]
@Immersion95 I have turned off that fix upscale bleeding option as your suggestion but the sprite on CVS2 game is still broken especially if the character moving.

**Comment by blisstik** [comment]
Windows platform with Nvidia graphics
RetroArch 1.20
Flycast 130675a

The issue still persists. I did notice that with "Fix Upscale Bleeding" option ON, Ryu's super hadoken has more of those vertical lines. When OFF, it is more spaced out like in the image on the first post.

**Comment by HebuSan** [comment]
Same for me, the issue still persists as described above

**Comment by Immersion95** [comment]
> [@Immersion95](https://github.com/Immersion95) I have turned off that fix upscale bleeding option as your suggestion but the sprite on CVS2 game is still broken especially if the character moving.

CVS2 isn't broken, do you have a screenshot ?

MVC2 sprite glitch only happen at higher resolution.
