### ISSUE TITLE
Regressions in Nightmare Creatures II since April 15 nightly

### ISSUE THREAD

**Issue by EdHerdman** [flyinghead/flycast#634]
Platform / OS / Hardware: 
Vulkan renderer / Windows 11 Pro 21H2 / Ryzen 7 3700X, 32GB, Nvidia GTX 3060 with 511.79 drivers

**_Description of the Issue_**

Flycast standalone releases since commit d732140 on April 16th have crackling and stuttering audio in the first FMVs of Nightmare Creatures II, a Windows CE title. The affected videos are the Kalisto Entertainment logo video and the video immediately after. (Later in-game FMVs have even more issues including chroma blocks all over; I didn't test this explicitly in older builds as it's not as quickly accessible.)

Flycast builds from Feb 14 to April 15 show the videos just fine. I think older builds had a FMV problem similar to the new builds, but I've checked out the oldest standalone builds still available.

The latest build (commit 4302562 on May 15th) additionally crashes to desktop on reaching these FMVs or loading a savestate (and RA will crash to desktop when using the corresponding cores).

**_Debugging Steps Tested_**

Tested in both Retroarch 1.10.3 and standalone.
Standalone flycast builds tested: Feb. 14, 27; March 26; April 6, 10, 12, 15, 16; May 11, 13, 15.
RA cores tested: flycast cores from 5/2 and more recent.

**_Standalone steps to reproduce_**

Unzip file to folder, add BIOS, set content directory, switch renderer to Vulkan. No other settings changed. Load NC II CHD, fast-forward to videos, observe audio or crashes.

**Comment by flyinghead** [comment]
Good catch on the latest build crash. I just pushed a fix for this issue.

I also have a solution for the FMV performance regression issue but I need some time to make sure it doesn't break anything.

**Comment by flyinghead** [comment]
This should be fixed on the dev branch

**Comment by flyinghead** [comment]
and now on master

**Comment by ElTioRata** [comment]
This issue is still present on RetroArch for some reason.

**Comment by ElTioRata** [comment]
Nevermind, the issue is still present on both RetroArch and standalone.

**Comment by flyinghead** [comment]
Make sure to use a real BIOS and that Video > Delay Frame Swapping is enabled

**Comment by ElTioRata** [comment]
Fixed 👍

**Comment by ElTioRata** [comment]
Nvm, looks like the audio only fixed itself on the initial logo videos, but the video that plays after starting a new game still stutters.

**Comment by ElTioRata** [comment]
Do I have to make a new issue?

**Comment by EdHerdman** [comment]
Yes, make a new issue, this one is closed and only I am receiving notifications.
