### ISSUE TITLE
SA2 Chao World Kills GPU

### ISSUE THREAD

**Issue by RinMaru** [flyinghead/flycast#908]
The Included emu.zip has settings used. I loaded my SA2 CHD and go into chao world and upon loading the emu will freeze and kill the GPU causing the drivers to reset.

Platform / OS / Hardware: 
Windows 11 22H2 2263.1250
Ryzen 5 5600X 
20GB DDR5 RAM
AMD Radeon RX6700XT 12GB 22.11.2

Github hash: 493ccc27

[emu.zip](https://github.com/flyinghead/flycast/files/10589109/emu.zip)

**Comment by flyinghead** [comment]
I cannot reproduce the issue on Nvidia using the exact same settings. I also enabled the Vulkan validation layers and they don't show any error. I tested the Chao lobby, garden and kindergarten.

Notes:
* Do not Force Windows CE on non-Windows CE games. This can affect performance and even lead to crashes. See #888 and #893
* Render to Texture > Copy to VRAM is automatically enabled for games that need it. You shouldn't have to enable it manually as it affects performance and quality of some textures

**Comment by RinMaru** [comment]
> I cannot reproduce the issue on Nvidia using the exact same settings. I also enabled the Vulkan validation layers and they don't show any error. I tested the Chao lobby, garden and kindergarten.
> 
> Notes:
> 
> * Do not Force Windows CE on non-Windows CE games. This can affect performance and even lead to crashes. See [Force Windows CE makes laggy intro and cutscenes in Sakura Taisen 3 and 4 #888](https://github.com/flyinghead/flycast/issues/888) and [Transitioning back from Full MMU makes arm64 and arm dynarec crash #893](https://github.com/flyinghead/flycast/issues/893)
> * Render to Texture > Copy to VRAM is automatically enabled for games that need it. You shouldn't have to enable it manually as it affects performance and quality of some textures

I also encountered the crash on Rayman 2. I think its just an AMD issue. as for shouldn't have to enable it why not get rid of the option?

**Comment by flyinghead** [comment]
It apparently happens when no transparent polygon is begin drawn during a frame. A work around could be to draw a dummy transparent triangle in that case.

Does the crash also happen with DirectX 11 in per pixel? With OpenGL?

I need to know which renderer(s) need this work around.

**Comment by RinMaru** [comment]
> It apparently happens when no transparent polygon is begin drawn during a frame. A work around could be to draw a dummy transparent triangle in that case.
> 
> Does the crash also happen with DirectX 11 in per pixel? With OpenGL?
> 
> I need to know which renderer(s) need this work around.

only happens in vk

**Comment by flyinghead** [comment]
I pushed a tentative workaround on the dev branch. Let me know if it fixes the crash.

**Comment by RinMaru** [comment]
> I pushed a tentative workaround on the dev branch. Let me know if it fixes the crash.

watch the CI builds and will grab it when its available

**Comment by RinMaru** [comment]
https://github.com/flyinghead/flycast/commit/aa97a6d64fb47d3ce0febaa575b26d975dd916e4 last currently known working build without crash

**Comment by flyinghead** [comment]
I reverted the previous tentative workaround and rolled back to the previous glslang compiler version that was used on the dev branch before before b37e6dc28d227f816552baf1aa86b9432c93bbdf.
Please check the latest dev build.

**Comment by RinMaru** [comment]
> I reverted the previous tentative workaround and rolled back to the previous glslang compiler version that was used on the dev branch before [b37e6dc](https://github.com/flyinghead/flycast/commit/b37e6dc28d227f816552baf1aa86b9432c93bbdf). Please check the latest dev build.

that fixes it ^^ thank you

**Comment by flyinghead** [comment]
This should be fixed on the master branch as well. When you get a chance, a confirmation would be appreciated.

**Comment by RinMaru** [comment]
> This should be fixed on the master branch as well. When you get a chance, a confirmation would be appreciated.

yep its fixed in both

**Comment by scribam** [comment]
@RinMaru Do you mind trying this build as well? https://github.com/scribam/flycast/suites/10861085390/artifacts/547649164
It's from https://github.com/scribam/flycast/commit/eb23c22f9081fccbb726784af201b8a53b7cfdf3 which is the master branch + glslang 12.0.0 (sdk-1.3.239.0)

**Comment by RinMaru** [comment]
> @RinMaru Do you mind trying this build as well? https://github.com/scribam/flycast/suites/10861085390/artifacts/547649164
> It's from https://github.com/scribam/flycast/commit/eb23c22f9081fccbb726784af201b8a53b7cfdf3 which is the master branch + glslang 12.0.0 (sdk-1.3.239.0)
> 
> 
> 

Nope its broken

**Comment by flyinghead** [comment]
I still don't know which glslang change is causing the crash.
I spotted this one: https://github.com/KhronosGroup/glslang/commit/228c67228a181ac299df2a1c09a322dcc9bb0cdc
Apparently glslang upgraded to using SPIRV 1.6. This might trigger new driver bugs (?).

**Comment by scribam** [comment]
Thanks for your feedback @RinMaru
Can you try also this one? I made a slight change regarding the shader version used
https://github.com/scribam/flycast/suites/10865151156/artifacts/547946021

**Comment by RinMaru** [comment]
> Thanks for your feedback @RinMaru Can you try also this one? I made a slight change regarding the shader version used https://github.com/scribam/flycast/suites/10865151156/artifacts/547946021

works
